name: Build and deploy backend to Azure Web App - coffee-shop-backend

on:
  push:
    branches:
      - main
      - preview
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Create .env to backend directory
        run: |
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> backend/.env
          echo "RAZORPAY_KEY=${{ secrets.RAZORPAY_KEY }}" >> backend/.env
          echo "RAZORPAY_SECRET=${{ secrets.RAZORPAY_SECRET }}" >> backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> backend/.env

      - name: Prepare artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'coffee-shop-backend'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7C489FB05F6F42C191B3DC414E2FE7C1 }}
